"""Tests for scripts/verify_report.py.

Invariants:
  INV-1  Aggregator output is deterministic regardless of filesystem enumeration order.
  INV-2  A report missing the Summary table is collected as a parse error, run continues.
  INV-3  A claim row with a status outside the allowed vocabulary raises ValueError.

Critical paths:
  - Empty verification/ directory → totals all 0, elements={}.
  - One synthetic report (3 verified + 1 discrepancy) → per-element and totals match.
  - Two synthetic reports → both appear in the aggregate.

Failure modes:
  - Malformed Summary table (no separator row) → ParseError with file path in message.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

# Make scripts/ importable without installing it.
_SCRIPTS_DIR = Path(__file__).resolve().parents[1] / "scripts"
sys.path.insert(0, str(_SCRIPTS_DIR))

from verify_report import (  # noqa: E402
    ParseError,
    aggregate_reports,
    parse_claims_table,
    parse_report,
    parse_summary_table,
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_VALID_REPORT_TEMPLATE = """\
# Verification: {symbol}

- Element: {name} ({symbol})
- Snapshot year: {year}
- Verifier: test_agent
- Date: 2026-04-11

## Summary

| Metric | Count |
|---|---|
| verified | {verified} |
| discrepancy | {discrepancy} |
| inferred | {inferred} |
| source_unreachable | {source_unreachable} |

## Claims

| Claim location | Value in YAML | Source id | Status | Evidence |
|---|---|---|---|---|
{claim_rows}
## Notes
Generated by test suite.
"""


def _make_report(
    symbol: str = "Co",
    name: str = "cobalt",
    year: int = 2025,
    verified: int = 0,
    discrepancy: int = 0,
    inferred: int = 0,
    source_unreachable: int = 0,
    claim_rows: str = "",
) -> str:
    return _VALID_REPORT_TEMPLATE.format(
        symbol=symbol,
        name=name,
        year=year,
        verified=verified,
        discrepancy=discrepancy,
        inferred=inferred,
        source_unreachable=source_unreachable,
        claim_rows=claim_rows,
    )


def _write_report(tmp_path: Path, filename: str, content: str) -> Path:
    p = tmp_path / filename
    p.write_text(content, encoding="utf-8")
    return p


# ---------------------------------------------------------------------------
# INV-1: deterministic output regardless of filesystem order
# ---------------------------------------------------------------------------


def test_inv1_deterministic_regardless_of_order(tmp_path: Path) -> None:
    """Aggregator sorts elements by symbol; output is always alphabetically ordered."""
    _write_report(tmp_path, "Nd.md", _make_report(symbol="Nd", name="neodymium", verified=2))
    _write_report(tmp_path, "Co.md", _make_report(symbol="Co", name="cobalt", verified=5, discrepancy=1))
    _write_report(tmp_path, "Ga.md", _make_report(symbol="Ga", name="gallium", inferred=3))

    summary, errors = aggregate_reports(tmp_path)
    assert errors == []
    assert list(summary["elements"].keys()) == ["Co", "Ga", "Nd"]
    assert summary["elements"]["Co"] == {"verified": 5, "discrepancy": 1, "inferred": 0, "source_unreachable": 0}
    assert summary["elements"]["Nd"] == {"verified": 2, "discrepancy": 0, "inferred": 0, "source_unreachable": 0}
    assert summary["elements"]["Ga"] == {"verified": 0, "discrepancy": 0, "inferred": 3, "source_unreachable": 0}


# ---------------------------------------------------------------------------
# INV-2: missing Summary table → parse error, no crash
# ---------------------------------------------------------------------------


def test_inv2_missing_summary_does_not_crash(tmp_path: Path) -> None:
    """A report without ## Summary is logged as a parse error; the run continues."""
    _write_report(tmp_path, "Co.md", "# Verification: Co\n\nNo summary section here.\n")
    summary, errors = aggregate_reports(tmp_path)
    assert len(errors) == 1
    assert "Co.md" in errors[0]
    assert "Summary" in errors[0]
    # The run produced a valid (empty) summary
    assert summary["elements"] == {}
    assert summary["totals"] == {"verified": 0, "discrepancy": 0, "inferred": 0, "source_unreachable": 0}


def test_inv2_parse_error_raised_directly(tmp_path: Path) -> None:
    """parse_summary_table raises ParseError when ## Summary is absent."""
    text = "# Verification: Co\n\nNo summary here.\n"
    path = tmp_path / "Co.md"
    path.write_text(text)
    with pytest.raises(ParseError, match="Summary"):
        parse_summary_table(path, text)


# ---------------------------------------------------------------------------
# INV-3: invalid claim status raises ValueError
# ---------------------------------------------------------------------------


def test_inv3_invalid_claim_status_raises_on_parse_report(tmp_path: Path) -> None:
    """parse_report raises ValueError when a Claims row has an unknown status."""
    bad_claim = "| production[0].mine.value | 100 t | src_x | INVALID_STATUS | evidence |\n"
    content = _make_report(symbol="Co", verified=1, claim_rows=bad_claim)
    path = _write_report(tmp_path, "Co.md", content)
    with pytest.raises(ValueError, match="INVALID_STATUS"):
        parse_report(path)


def test_inv3_invalid_claim_status_raises_on_parse_claims(tmp_path: Path) -> None:
    """parse_claims_table raises ValueError on unknown status."""
    text = _make_report(
        symbol="Co",
        claim_rows="| loc | val | src | unknown_val | evidence |\n",
    )
    path = tmp_path / "Co.md"
    path.write_text(text)
    with pytest.raises(ValueError, match="unknown_val"):
        parse_claims_table(path, text)


# ---------------------------------------------------------------------------
# Critical path: empty directory
# ---------------------------------------------------------------------------


def test_empty_directory_produces_zero_totals(tmp_path: Path) -> None:
    """No .md files → elements={}, totals all 0."""
    summary, errors = aggregate_reports(tmp_path)
    assert errors == []
    assert summary["elements"] == {}
    assert summary["totals"] == {"verified": 0, "discrepancy": 0, "inferred": 0, "source_unreachable": 0}
    assert summary["snapshot_year"] is None


def test_skip_files_are_excluded(tmp_path: Path) -> None:
    """README.md and _template.md must not be parsed as element reports."""
    (tmp_path / "README.md").write_text("# readme\n")
    (tmp_path / "_template.md").write_text("# template\n")
    summary, errors = aggregate_reports(tmp_path)
    assert errors == []
    assert summary["elements"] == {}


# ---------------------------------------------------------------------------
# Critical path: one file with 3 verified + 1 discrepancy
# ---------------------------------------------------------------------------


def test_single_report_aggregates_correctly(tmp_path: Path) -> None:
    """Single report: per-element and totals both reflect the Summary table values."""
    _write_report(tmp_path, "Co.md", _make_report(symbol="Co", verified=3, discrepancy=1, year=2025))
    summary, errors = aggregate_reports(tmp_path)
    assert errors == []
    assert summary["elements"]["Co"] == {"verified": 3, "discrepancy": 1, "inferred": 0, "source_unreachable": 0}
    assert summary["totals"] == {"verified": 3, "discrepancy": 1, "inferred": 0, "source_unreachable": 0}
    assert summary["snapshot_year"] == 2025


# ---------------------------------------------------------------------------
# Critical path: two files → both in aggregate
# ---------------------------------------------------------------------------


def test_two_reports_both_appear_in_aggregate(tmp_path: Path) -> None:
    """Two reports → both symbols appear in elements; totals sum across both."""
    _write_report(tmp_path, "Co.md", _make_report(symbol="Co", verified=4, discrepancy=1))
    _write_report(tmp_path, "Nd.md", _make_report(symbol="Nd", verified=2, source_unreachable=1))
    summary, errors = aggregate_reports(tmp_path)
    assert errors == []
    assert set(summary["elements"].keys()) == {"Co", "Nd"}
    assert summary["totals"]["verified"] == 6
    assert summary["totals"]["discrepancy"] == 1
    assert summary["totals"]["source_unreachable"] == 1
    assert summary["totals"]["inferred"] == 0


# ---------------------------------------------------------------------------
# Failure mode: malformed Summary table (no separator row)
# ---------------------------------------------------------------------------


def test_malformed_summary_table_produces_clear_error(tmp_path: Path) -> None:
    """A Summary table without the separator row produces a ParseError with the file path."""
    # Drop the separator row so _parse_md_table returns None
    broken = """\
# Verification: Co

- Element: Cobalt (Co)
- Snapshot year: 2025

## Summary

| Metric | Count |
| verified | 3 |
| discrepancy | 0 |

## Claims

| Claim location | Value in YAML | Source id | Status | Evidence |
|---|---|---|---|---|

## Notes
"""
    path = _write_report(tmp_path, "Co.md", broken)
    with pytest.raises(ParseError) as exc_info:
        parse_report(path)
    assert "Co.md" in str(exc_info.value)

    # Same scenario via the aggregator: error collected, no crash
    _, errors = aggregate_reports(tmp_path)
    assert len(errors) == 1
    assert "Co.md" in errors[0]


# ---------------------------------------------------------------------------
# Claims table: valid statuses all accepted
# ---------------------------------------------------------------------------


def test_all_valid_statuses_accepted(tmp_path: Path) -> None:
    """Each of the four allowed statuses should parse without error."""
    claim_rows = "\n".join(
        f"| loc{i} | val | src | {status} | evidence |"
        for i, status in enumerate(["verified", "discrepancy", "inferred", "source_unreachable"])
    )
    content = _make_report(symbol="Co", verified=1, discrepancy=1, inferred=1, source_unreachable=1, claim_rows=claim_rows + "\n")
    path = _write_report(tmp_path, "Co.md", content)
    symbol, counts, _ = parse_report(path)
    assert symbol == "Co"
    assert counts == {"verified": 1, "discrepancy": 1, "inferred": 1, "source_unreachable": 1}  # from Summary table
